#!/usr/bin/env bash
#
# The purpose of this script is running pre-start

set -e  # exit immediately if a simple command exits with a non-zero status
set -u # report the usage of uninitialized variables
echo pre-start > /tmp/pre-start
date >> /tmp/pre-start
